/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CampaignsCampaignIdRouteImport } from './routes/campaigns_.$campaignId'
import { Route as CampaignsCreateRouteImport } from './routes/campaigns.create'
import { Route as CampaignsCampaignIdEditRouteImport } from './routes/campaigns_.$campaignId.edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdRoute = CampaignsCampaignIdRouteImport.update({
  id: '/campaigns_/$campaignId',
  path: '/campaigns/$campaignId',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCreateRoute = CampaignsCreateRouteImport.update({
  id: '/campaigns/create',
  path: '/campaigns/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsCampaignIdEditRoute = CampaignsCampaignIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => CampaignsCampaignIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/campaigns/create': typeof CampaignsCreateRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteWithChildren
  '/campaigns/$campaignId/edit': typeof CampaignsCampaignIdEditRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/campaigns/create': typeof CampaignsCreateRoute
  '/campaigns/$campaignId': typeof CampaignsCampaignIdRouteWithChildren
  '/campaigns/$campaignId/edit': typeof CampaignsCampaignIdEditRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/campaigns/create': typeof CampaignsCreateRoute
  '/campaigns_/$campaignId': typeof CampaignsCampaignIdRouteWithChildren
  '/campaigns_/$campaignId/edit': typeof CampaignsCampaignIdEditRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/campaigns/create'
    | '/campaigns/$campaignId'
    | '/campaigns/$campaignId/edit'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/campaigns/create'
    | '/campaigns/$campaignId'
    | '/campaigns/$campaignId/edit'
  id:
    | '__root__'
    | '/'
    | '/campaigns/create'
    | '/campaigns_/$campaignId'
    | '/campaigns_/$campaignId/edit'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CampaignsCreateRoute: typeof CampaignsCreateRoute
  CampaignsCampaignIdRoute: typeof CampaignsCampaignIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns_/$campaignId': {
      id: '/campaigns_/$campaignId'
      path: '/campaigns/$campaignId'
      fullPath: '/campaigns/$campaignId'
      preLoaderRoute: typeof CampaignsCampaignIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns/create': {
      id: '/campaigns/create'
      path: '/campaigns/create'
      fullPath: '/campaigns/create'
      preLoaderRoute: typeof CampaignsCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns_/$campaignId/edit': {
      id: '/campaigns_/$campaignId/edit'
      path: '/edit'
      fullPath: '/campaigns/$campaignId/edit'
      preLoaderRoute: typeof CampaignsCampaignIdEditRouteImport
      parentRoute: typeof CampaignsCampaignIdRoute
    }
  }
}

interface CampaignsCampaignIdRouteChildren {
  CampaignsCampaignIdEditRoute: typeof CampaignsCampaignIdEditRoute
}

const CampaignsCampaignIdRouteChildren: CampaignsCampaignIdRouteChildren = {
  CampaignsCampaignIdEditRoute: CampaignsCampaignIdEditRoute,
}

const CampaignsCampaignIdRouteWithChildren =
  CampaignsCampaignIdRoute._addFileChildren(CampaignsCampaignIdRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CampaignsCreateRoute: CampaignsCreateRoute,
  CampaignsCampaignIdRoute: CampaignsCampaignIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
